# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BebeLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BebeLogin
pod 'TextFieldEffects'
pod 'KakaoSDKCommon'
pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'
pod 'naveridlogin-sdk-ios'
pod 'GoogleSignIn'
pod 'SnapKit', '~> 5.0.0'
pod 'STTextView'
pod 'IQKeyboardManagerSwift'
end
